name: Deploy Dos RPAs de TJ Bots B4 No Servidor De Homologacao Unifique

on: 
  push:
    branches:
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST_HOMOLOG }}
        username: ${{ secrets.REMOTE_USER_HOMOLOG }}
        key: ${{ secrets.SSH_PRIVATE_KEY_HOMOLOG }}
        port: ${{ secrets.PORT_HOMOLOG }}
        script: |
          cd /opt/apps
          # Clone o repositório se não existir
          if [ ! -d "${{ secrets.REPO_NAME }}" ]; then
            git clone -b homolog "${{ secrets.REPO_URL }}" ${{ secrets.REPO_NAME }}
          fi
          
          # Atualiza o repositório
          cd ${{ secrets.REPO_NAME }}
          git fetch origin
          git reset --hard origin/homolog
          git checkout homolog
          git pull origin homolog

          ./build.sh

      env:
          key: ${{secrets.SSH_PRIVATE_KEY_HOMOLOG}}
          host: ${{secrets.REMOTE_HOST_HOMOLOG}}
          username: ${{secrets.REMOTE_USER_HOMOLOG}}
          REPO_URL: ${{ secrets.REPO_URL }}
